ProgramacionWeb/biblio/config/routes.rb
Rails.application.routes.draw do
  resources :libros
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

ProgramacionWeb/biblio/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ProgramacionWeb/biblio/app/models/libro.rb
class Libro < ApplicationRecord
end

ProgramacionWeb/biblio/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ProgramacionWeb/biblio/app/controllers/libros_controller.rb
class LibrosController < ApplicationController
  before_action :set_libro, only: [:show, :edit, :update, :destroy]

  # GET /libros
  # GET /libros.json
  def index
    @libros = Libro.all
  end

  # GET /libros/1
  # GET /libros/1.json
  def show
  end

  # GET /libros/new
  def new
    @libro = Libro.new
  end

  # GET /libros/1/edit
  def edit
  end

  # POST /libros
  # POST /libros.json
  def create
    @libro = Libro.new(libro_params)

    respond_to do |format|
      if @libro.save
        format.html { redirect_to @libro, notice: 'Libro was successfully created.' }
        format.json { render :show, status: :created, location: @libro }
      else
        format.html { render :new }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libros/1
  # PATCH/PUT /libros/1.json
  def update
    respond_to do |format|
      if @libro.update(libro_params)
        format.html { redirect_to @libro, notice: 'Libro was successfully updated.' }
        format.json { render :show, status: :ok, location: @libro }
      else
        format.html { render :edit }
        format.json { render json: @libro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libros/1
  # DELETE /libros/1.json
  def destroy
    @libro.destroy
    respond_to do |format|
      format.html { redirect_to libros_url, notice: 'Libro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libro
      @libro = Libro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libro_params
      params.require(:libro).permit(:nombre, :descripcion, :precio)
    end
end

ProgramacionWeb/biblio/app/helpers/application_helper.rb
module ApplicationHelper
end

ProgramacionWeb/biblio/app/helpers/libros_helper.rb
module LibrosHelper
end

ProgramacionWeb/biblio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ProgramacionWeb/biblio/app/views/libros/_form.html.erb
<%= form_with(model: libro, local: true) do |form| %>
  <% if libro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(libro.errors.count, "error") %> prohibited this libro from being saved:</h2>

      <ul>
      <% libro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :libro_nombre %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion, id: :libro_descripcion %>
  </div>

  <div class="field">
    <%= form.label :precio %>
    <%= form.text_field :precio, id: :libro_precio %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ProgramacionWeb/biblio/app/views/libros/edit.html.erb
<h1>Editing Libro</h1>

<%= render 'form', libro: @libro %>

<%= link_to 'Show', @libro %> |
<%= link_to 'Back', libros_path %>

ProgramacionWeb/biblio/app/views/libros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libros</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripcion</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libros.each do |libro| %>
      <tr>
        <td><%= libro.nombre %></td>
        <td><%= libro.descripcion %></td>
        <td><%= libro.precio %></td>
        <td><%= link_to 'Show', libro , class:"btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_libro_path(libro) , class:"btn btn-success" %></td>
        <td><%= link_to 'Destroy', libro, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-success" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libro', new_libro_path, class:"btn btn-success" %>

ProgramacionWeb/biblio/app/views/libros/new.html.erb
<h1>New Libro</h1>

<%= render 'form', libro: @libro %>

<%= link_to 'Back', libros_path %>

ProgramacionWeb/biblio/app/views/libros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @libro.nombre %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @libro.descripcion %>
</p>

<p>
  <strong>Precio:</strong>
  <%= @libro.precio %>
</p>

<%= link_to 'Edit', edit_libro_path(@libro) %> |
<%= link_to 'Back', libros_path %>